services:
  
  sqlserver_slave:
    image : mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_slave
    hostname: 3e7de6338edd
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      MSSQL_PID: "Developer"
      MSSQL_AGENT_ENABLED: True
      MSSQL_ENABLE_HADR: True
    restart: unless-stopped
    ports:
      - "1434:1433"
    volumes:
      - sqlserver_slave_data:/var/opt/mssql
      - /home/icescream/Projects/Stage/stage/repldata:/var/opt/mssql/repldata
      - /home/icescream/Projects/Stage/stage/backups:/var/opt/mssql/backups

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $$MSSQL_SA_PASSWORD -No -Q 'SELECT 1' || exit 1"
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - replication
    
volumes:
  sqlserver_slave_data:
    
networks:
  replication:
    external: true
